### ISSUE TITLE
Module works fine but the elasticsearch module does not respond

### ISSUE THREAD

**Issue by shetsu01** [yokawasa/logstash-output-azure_loganalytics#14]
We are using the module on our testing environment and it has been added to our logstash.conf. The problem we are facing now is with the elasticsearch module. The logs are now going properly to Log Analytics but does not go to Elasticsearch. 

Any idea what could be the issue here?

Our logstash config looks like this.

output {

     if [fields][log_code] == "ins_app_log"  {
        if [applog_meta][sys] {
             elasticsearch {
                  hosts => ["https://develasticsearch.dev.net:9200"]
                  index => "applog-%{[fields][lifecycle]}-%{[applog_meta][sys]}-%{+YYYY-'w'ww}"
                  document_type => "_doc"
                  ssl => true
                  truststore => "/etc/logstash/security/elk-ins-truststore.jks"
                  truststore_password => 'DFdfwfwdkjd$$$$$!'
                  ssl_certificate_verification => false
                  user => logstash
                  password => "dvffjf@@3###"
              }
             azure_loganalytics {
                  customer_id => "$$$$$$$-cb6d-495b-%%%%%%-970bb08babf0"
                  shared_key => "tQ7sUyvX7F0UmA7cNs1yoOdc2**************/eXLNagIB5oSl********************=="
                  log_type => "applog"
                  key_names  => [] ## list of Key names
                  key_types => {}
                  flush_items => 1000
                  flush_interval_time => 1
              }
           # for debug
                  stdout { codec => rubydebug }
         }
     }

}

**Comment by yokawasa** [comment]
@shetsu01 sorry I don't have any idea on this issue. 

Please open the issue in more relevant place. 

- https://github.com/elastic/logstash
or more boradly
- https://discuss.elastic.co/

let me close the issue
