### ISSUE TITLE
error sending data to azureloganalytics 

### ISSUE THREAD

**Issue by MarcosxDeveloper** [yokawasa/logstash-output-azure_loganalytics#18]
[ERROR] 2021-03-18 16:03:30.257 [[main]>worker0] azureloganalytics - Exception occured in posting to DataCollector API as log type test-type: 'uninitialized constant Azure::Loganalytics::Datacollectorapi::Client::ConfigError', data=>[]

**Comment by MarcosxDeveloper** [comment]
I fix my problem replacing my log type name,

from `%{source.provider}-%{source.name} ` to `%{source.provider}_%{source.name}`

I recommend not using the character "-" to save data in azure.

**Comment by yokawasa** [comment]
@MarcosxDeveloper 
Thank you for your posting the issue.
Yes, `_` must not be contained in the log_type. 

I've already added the description on the log_type like this in [README.md](https://github.com/yokawasa/logstash-output-azure_loganalytics/blob/master/README.md#configuration): 

> log_type (required) - The name of the event type that is being submitted to Log Analytics. It must only contain alpha numeric and _, and not exceed 100 chars. sprintf syntax like %{my_log_type} is supported.
