### ISSUE TITLE
Incompatible ruby version for rest-client

### ISSUE THREAD

**Issue by gmousset** [yokawasa/logstash-output-azure_loganalytics#2]
Hello, 

I try to install the plugin but I've an error:

/opt/logstash/bin/logstash-plugin install logstash-output-azure_loganalytics

Validating logstash-output-azure_loganalytics
Installing logstash-output-azure_loganalytics
Error Bundler::InstallError, retrying 1/10
An error occurred while installing rest-client (2.0.1), and Bundler cannot continue.
Make sure that `gem install rest-client -v '2.0.1'` succeeds before bundling.
WARNING: SSLSocket#session= is not supported

I think there's an incompatibility, rest-client 2.0.1 need ruby 2.0.0 and the logstash jruby version is 1.9

The gemspec should precise a previous version of rest-client.

**Comment by yokawasa** [comment]
@gmousset 
My apologies for responding to you this late. I'm looking into this, and get back to you shortly

**Comment by yokawasa** [comment]
@gmousset 
Thank you so much for your PR!! I partly merged it into master branch and published logstash-output-azure_loganalytics-0.1.1.
https://rubygems.org/gems/logstash-output-azure_loganalytics/versions/0.1.1
